# Generated by Django 4.2 on 2026-03-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="sensor_images/"),
        ),
    ]
