# Generated by Django 4.2 on 2026-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sensordata_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="device_id",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
    ]
