# Generated by Django 4.2 on 2026-03-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_sensordata_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="created_at",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="reading_id",
            field=models.CharField(default="default", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="device_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="humidity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="leaves/"),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="soil_moisture",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
